[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
default-run = "aoc"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1_2"
path = "src/day1_2.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
regex = "1.11.1"
