[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day1_2"
path = "src/day1_2.rs"

[[bin]]
name = "day2"
path = "src/daybin2.rs"

[dependencies]
